/**
 * All user-facing copy for onboarding, auth, setup and attribution (BRD 10: one strings file
 * so Hindi/Hinglish can be added later). Voice: second person, short, no emoji, no exclamation marks.
 * Persona-specific goal/why suggestions live in src/config/onboarding.ts.
 */
export const strings = {
  common: {
    back: "Back",
    continue: "Continue",
    skip: "Skip",
    notNow: "Not now",
    openSettings: "Open settings",
    required: "Required",
    recommended: "Recommended",
    tryAgain: "Something went wrong. Try again.",
    retry: "Try again",
    offline: "You're offline. Connect to the internet and try again.",
  },

  onboarding: {
    progress: (step: number, total: number) => `Step ${step} of ${total}`,

    welcome: {
      eyebrow: "RemindU",
      title: "Scroll less. Do what you said you would.",
      subtitle: "Set a goal. Your phone asks you to prove it.",
      cta: "Get started",
      haveAccount: "I already have an account",
    },

    persona: {
      title: "What best describes you?",
      labels: {
        student: "Student",
        exam_prep: "Exam prep",
        professional: "Working professional",
        founder: "Side hustle / founder",
        creator: "Creator",
        teacher: "Teacher",
        other: "Something else",
      },
      descriptions: {
        exam_prep: "JEE, NEET, UPSC, CAT",
      } as Partial<Record<string, string>>,
    },

    goal: {
      title: "What are you working toward?",
      subtitle: "Pick one. You can change it anytime.",
      writeOwn: "Write my own",
      placeholder: "Building my startup, not scrolling",
      tooShort: "At least 3 characters.",
      counter: (n: number, max: number) => `${n}/${max}`,
    },

    why: {
      title: "Why does this matter to you?",
      subtitle: "We'll show this at every check-in.",
      ownWords: "In my own words",
      placeholder: "Because...",
    },

    apps: {
      title: "Which apps pull you away?",
      subtitle: "Only these count against you. Everything else is fine.",
      suggested: "Suggested",
      seeAll: "See all apps",
      hideAll: "Show fewer apps",
      selectAll: "Select all",
      clear: "Clear",
      cta: "Looks right",
      pickOne: "Pick at least one app",
      selectedCount: (n: number) => `${n} app${n === 1 ? "" : "s"} selected`,
      loading: "Finding your apps",
    },

    permissions: {
      title: "A few permissions, and you're set.",
      subtitle: "Each one opens your phone's settings. Come back here when you're done.",
      cta: "Continue",
      items: {
        usage: {
          title: "Usage access",
          body: "Notices when you open the apps you picked. Your usage never leaves your phone.",
          reason: "Android needs this to tell which app is on screen.",
        },
        overlay: {
          title: "Display over other apps",
          body: "Brings your check-in to the front when time is up.",
          reason: "Without it, the check-in can't appear over Instagram or YouTube.",
        },
        notifications: {
          title: "Notifications",
          body: "Shows your session timer and check-in reminders.",
          reason: "Android 13 and up asks before an app can show notifications.",
        },
        battery: {
          title: "Keep RemindU running",
          body: "Stops your phone from closing RemindU in the background.",
          reason: "Some phones close background apps to save battery, which stops your session.",
        },
      },
      brandGuideTitle: (brand: string) => `On ${brand} phones`,
      brandGuideLink: "Full guide for your phone",
    },

    trial: {
      title: (days: number) => `Try RemindU Pro free for ${days} days`,
      maybeLater: "Maybe later",
      today: "Today",
      todayBody: "Full access to every check-in task and insight.",
      reminder: (day: number) => `Day ${day}`,
      reminderBody: "We'll remind you before your trial ends.",
      ends: (day: number) => `Day ${day}`,
      endsBody: (price: string) => `Your trial ends. Then ${price}. Cancel anytime.`,
      cta: "Start free trial",
    },
  },

  auth: {
    signIn: {
      title: "Save your streak.",
      subtitle: "Your goal and apps are ready. Sign in so you never lose progress.",
      titleReturning: "Welcome back.",
      subtitleReturning: "Sign in to pick up where you left off.",
      google: "Continue with Google",
      email: "Continue with email",
      terms: "By continuing you agree to the Terms and Privacy Policy.",
      googleCancelled: "Google sign-in was cancelled.",
    },
    email: {
      title: "What's your email?",
      subtitle: "We'll send you a 6-digit code. No password needed.",
      placeholder: "you@example.com",
      invalid: "Enter a valid email address.",
      cta: "Send code",
      sending: "Sending…",
    },
    verify: {
      title: "Enter your code",
      subtitle: (email: string) => `We sent a 6-digit code to ${email}.`,
      cta: "Verify",
      verifying: "Verifying…",
      wrongCode: "That code didn't work. Check it and try again.",
      expired: "That code has expired. Send a new one.",
      resend: "Send a new code",
      resendIn: (s: number) => `Send a new code in ${s}s`,
      resent: "New code sent.",
      changeEmail: "Use a different email",
    },
  },

  tabs: {
    home: "Home",
    sessions: "Sessions",
    add: "Add apps",
    goals: "Goals",
    profile: "Profile",
  },

  permissionBanner: {
    title: "RemindU can't check in yet",
    body: (missing: string) => `Turn on ${missing} so your timers work.`,
    cta: "Fix",
  },

  home: {
    greeting: { morning: "Good morning", afternoon: "Good afternoon", evening: "Good evening", night: "Good night" },
    greetingName: (greeting: string, name: string) => `${greeting}, ${name}`,
    streak: "Day streak",
    screenTime: "Screen time today",
    mostUsed: "Most used app",
    none: "—",
    noAccess: "Needs usage access",
    appsTitle: "Your apps",
    seeAll: "See all",
    emptyTitle: "No apps yet",
    emptyBody: "Tap + to pick the apps that pull you away. Each one gets its own timer.",
    emptyCta: "Add apps",
  },

  status: {
    waiting: "Starts when you open it",
    counting: "Counting down",
    paused: "Paused",
    time_up: "Time's up",
    cooldown: "On a break",
  },

  sessions: {
    title: "Sessions",
    subtitle: "Each timer only moves while its app is open.",
    active: "Active",
    past: "Ended",
    left: "left",
    of: (length: string) => `of ${length}`,
    opens: (n: number) => `Opened ${n} time${n === 1 ? "" : "s"} today`,
    emptyTitle: "No sessions running",
    emptyBody: "Add an app with + and its timer shows up here.",
    endedOn: (date: string) => `Ended ${date}`,
  },

  add: {
    title: "Add apps",
    searchPlaceholder: "Search apps",
    noResults: (q: string) => `No apps match “${q}”`,
    running: "Has a timer",
    next: (n: number) => (n ? `Next · ${n} app${n === 1 ? "" : "s"}` : "Pick at least one app"),
    setupTitle: "Session settings",
    setupSubtitle: (n: number) =>
      `${n} app${n === 1 ? "" : "s"} selected. Each timer starts the first time you open the app.`,
    lengthLabel: "Session length",
    custom: "Custom",
    customHours: "Hours",
    customMinutes: "Minutes",
    frequencyLabel: "Check-in frequency",
    frequencyHelp: {
      once: "One check-in when the time is up, then the timer ends.",
      every: "When the time is up, the app stays blocked for the hours you pick. Then the same length starts again.",
      continuous: "After each check-in, the same length starts again.",
    },
    everyLabel: "Next round after",
    done: "Done",
    adding: "Adding…",
    back: "Change apps",
    loading: "Finding your apps",
  },

  /** Session length and frequency labels, shared by the Add sheet and the session screens. */
  length: {
    presets: [10, 20, 30, 60, 120] as const,
    label: (min: number) => {
      if (min < 60) return `${min} min`;
      const h = Math.floor(min / 60);
      const m = min % 60;
      return m ? `${h}h ${m}m` : `${h} hr`;
    },
    frequencies: { once: "Once", every: "Every X hrs", continuous: "Continuous" },
    everyHours: (h: number) => `${h}h`,
    frequencySummary: { once: "Once", every: (h: number) => `Every ${h}h`, continuous: "Continuous" },
  },

  session: {
    untilCheckIn: "until check-in",
    untilNextRound: "until next round",
    waitingHelp: "The timer starts the first time you open this app.",
    pausedHelp: "The timer only moves while this app is open.",
    countingHelp: (app: string) => `${app} is open, so the timer is running.`,
    goalLabel: "Your goal",
    details: "Details",
    length: "Session length",
    frequency: "Check-in frequency",
    added: "Added",
    started: "First opened",
    notYet: "Not yet",
    checkIns: "Check-ins",
    logTitle: "Time log",
    logEmpty: "No visits yet. Each time you open the app it shows up here.",
    logNow: "now",
    logRow: (from: string, to: string) => `${from} – ${to}`,
    today: "Today",
    yesterday: "Yesterday",
    end: "End session",
    endConfirmTitle: "End this session?",
    endConfirmBody: "The timer stops and the session moves to Ended.",
    endConfirm: "End session",
    cancel: "Keep going",
    timeUpEyebrow: (app: string) => `Time's up on ${app}`,
    timeUpTitle: "This is what you said you wanted.",
    timeUpBody: "Take one slow breath before you decide.",
    breatheIn: "Breathe in",
    breatheOut: "Breathe out",
    keepGoing: (label: string) => `Start next ${label}`,
    nextRoundAt: (label: string, time: string) => `Your next ${label} opens at ${time}.`,
    finish: "Finish session",
    notFound: "This session doesn't exist anymore.",
    backHome: "Back to home",
    ended: "Ended",
  },

  goals: {
    title: "Goals",
    subtitle: "What you're working toward, and the challenges you've set.",
    add: "New goal",
    focus: "Focus",
    focusHelp: "Shown on every check-in",
    setFocus: "Make focus",
    complete: "Mark done",
    delete: "Delete",
    deleteTitle: "Delete this goal?",
    deleteBody: "This can't be undone.",
    completed: "Completed",
    challenge: (day: number, total: number) => `Day ${day} of ${total}`,
    openEnded: "Open-ended",
    emptyTitle: "No goals yet",
    emptyBody: "Add one with + at the top. Your focus goal shows at every check-in.",
    newTitle: "New goal",
    textLabel: "Goal",
    textPlaceholder: "Finish my thesis draft",
    whyLabel: "Why it matters",
    whyPlaceholder: "Because...",
    challengeLabel: "Make it a challenge",
    challengeOptions: { none: "No", 7: "7 days", 21: "21 days", 30: "30 days" } as Record<string, string>,
    makeFocus: "Make this my focus",
    save: "Save goal",
    saving: "Saving…",
  },

  profile: {
    settings: "Settings",
    streak: (n: number) => `${n} day streak`,
    activityTitle: "Activity",
    activityHelp: "Time spent in your tracked apps each day",
    less: "Less",
    more: "More",
    screenTimeTitle: "Screen time",
    ranges: { week: "Week", month: "Month", year: "Year" },
    dailyAverage: "Daily average",
    noData: "No screen time yet. It fills in as you use your phone.",
    overviewTitle: "Overview",
    avgSession: "Average session",
    peakTime: "Most used time",
    breaths: "Breaths taken",
    noValue: "—",
  },

  settings: {
    title: "Settings",
    sections: { general: "General", appearance: "Appearance", support: "Support", account: "Account" },
    notAvailable: "This page isn't available yet.",
    notifications: "Notifications",
    notificationsHelp: "Timer and check-in alerts",
    permissions: "Permissions",
    account: "Account details",
    appearance: "Dark mode",
    themes: { system: "System", light: "Light", dark: "Dark" },
    limits: "Daily app limits",
    help: "Help",
    privacy: "Privacy policy",
    signOut: "Sign out",
    signOutTitle: "Sign out?",
    signOutBody: "Your timers stop on this phone. Your goals stay saved to your account.",
    deleteAccount: "Delete account",
    deleteTitle: "Delete your account?",
    deleteBody: "Your goals, apps and history are permanently deleted. This can't be undone.",
    deleteConfirm: "Delete",
    cancel: "Cancel",
    version: (v: string) => `RemindU ${v}`,
    accountTitle: "Account details",
    nameLabel: "Name",
    emailLabel: "Email",
    signedInWith: "Signed in with",
    providers: { google: "Google", email: "Email code" } as Record<string, string>,
    memberSince: "Member since",
    save: "Save",
    saved: "Saved",
    helpTitle: "Help",
    contact: "Email support",
    faq: [
      {
        q: "When does a timer start?",
        a: "The first time you open the app after adding it. Until then it waits and nothing counts.",
      },
      {
        q: "Why isn't my timer moving?",
        a: "It only counts while that app is on screen. Check that Usage access is on in Settings > Permissions.",
      },
      {
        q: "What happens when time is up?",
        a: "RemindU blocks the app and shows your goal. Take a breath, then start the next round or finish. With “Every X hrs”, the app stays blocked until the next round opens.",
      },
      {
        q: "My phone keeps closing RemindU",
        a: "Some phones stop background apps to save battery. Turn on \"Keep RemindU running\" in Permissions.",
      },
      {
        q: "Does my usage leave my phone?",
        a: "No. App usage and screen time stay on your phone. Only your goals and chosen apps sync to your account.",
      },
    ],
  },

  attribution: {
    title: "Nice, first session done.",
    subtitle: "Quick one: how did you find RemindU?",
    options: {
      creator: "A creator",
      instagram: "Instagram",
      youtube: "YouTube",
      friend: "A friend",
      other: "Other",
    },
    creatorLabel: "Which creator?",
    creatorPlaceholder: "Name or handle (optional)",
    cta: "Done",
  },
} as const;
